// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDegqwrjnVc1R717VSNXNp9g6vFM0ZpdNc',
    appId: '1:428281382475:web:a4bd5eb3f95e288b0eafce',
    messagingSenderId: '428281382475',
    projectId: 'sportsoverflow-c4a89',
    authDomain: 'sportsoverflow-c4a89.firebaseapp.com',
    storageBucket: 'sportsoverflow-c4a89.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxHqQ317e3Kg8UXYV7t49jiPROMVoo1-c',
    appId: '1:428281382475:android:0bb18a801cd748730eafce',
    messagingSenderId: '428281382475',
    projectId: 'sportsoverflow-c4a89',
    storageBucket: 'sportsoverflow-c4a89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcIuajN5UysTjzqPIW1VwVeJDrH0Xyi7Q',
    appId: '1:428281382475:ios:4c2aa9ab6a40b87d0eafce',
    messagingSenderId: '428281382475',
    projectId: 'sportsoverflow-c4a89',
    storageBucket: 'sportsoverflow-c4a89.appspot.com',
    iosClientId: '428281382475-3hulnmrq50tm0tqsnc5pedv4o59efbva.apps.googleusercontent.com',
    iosBundleId: 'com.example.sportsAppGreenEagles',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcIuajN5UysTjzqPIW1VwVeJDrH0Xyi7Q',
    appId: '1:428281382475:ios:ead96aa17c8e49a90eafce',
    messagingSenderId: '428281382475',
    projectId: 'sportsoverflow-c4a89',
    storageBucket: 'sportsoverflow-c4a89.appspot.com',
    iosClientId: '428281382475-t4terp8a8ljqnvcsb65o7ajmaljqgp3q.apps.googleusercontent.com',
    iosBundleId: 'com.example.sportsAppGreenEagles.RunnerTests',
  );
}
